[package]
name = "cchol-pm"
version = "0.1.1"
edition = "2024"
authors = ["Markku Sukanen <markku.sukanen@gmail.com>"]
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = "2"
quote = "1"

[badges]
maintenance = { status = "experimental" }
