[package]
name = "cchol-proto"
version = "0.1.0"
edition = "2024"
authors = ["Markku Sukanen <gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
dicebag = "0.3"

[badges]
maintenance = { status = "experimental" }